stages:
    - lint
    - i18n
    - release

before_script:
    - npm ci --cache .npm --prefer-offline

cache:
    paths:
        - ./.npm/

.lint:
    image: eu.gcr.io/vivid-planet/ubi/s2i-ubi8-nodejs14:limit7-19
    stage: lint
    interruptible: true
    only:
        - main
        - next
        - external_pull_requests
    tags:
        - docker

project-lint:
    extends: .lint
    script:
        - npx prettier -c .

packages-lint:
    extends: .lint
    script:
        - npm run lint

i18n:
    stage: i18n
    image: eu.gcr.io/vivid-planet/ubi/s2i-ubi8-nodejs14:limit7-19
    only:
        - main
    tags:
        - docker
    script:
        - npm run intl:extract
        - git clone https://github.com/vivid-planet/comet-admin-lang.git
        - cp -r lang/* comet-admin-lang/
        - cd comet-admin-lang
        - git config user.email "vivid-planet-bot@vivid-planet.com"
        - git add .
        - if [[ `git status --porcelain` ]]; then git commit -m "add translatable strings for $CI_COMMIT_SHA" && git remote rm origin && git remote add origin https://vivid-planet-bot:${GH_TOKEN}@github.com/vivid-planet/comet-admin-lang.git && git push --set-upstream origin master; fi

canary:
    image: eu.gcr.io/vivid-planet/ubi/s2i-ubi8-nodejs14:limit7-19
    stage: release
    tags:
        - docker
    only:
        - main
        - next
    except:
        variables:
            - $CI_COMMIT_MESSAGE =~ /^chore\(release\)/
    script:
        - npm run build
        - npm run publish:release -- --canary --preid=canary.$CI_PIPELINE_IID --dist-tag=canary --yes
