language: minimal

before_install:
    - curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
    - sudo apt install nodejs
    - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
    - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    - sudo apt update && sudo apt install yarn

jobs:
    include:
        - name: "Linting Project Root"
          script:
              - yarn install
              - yarn prettier -c .
        - name: "Linting Packages"
          script:
              - yarn install
              - yarn run lint
        - name: "Extracting String Resources"
          if: branch = master
          script:
              - yarn install
              - yarn run intl:extract
              - git clone https://github.com/vivid-planet/comet-admin-lang.git
              - cp -r lang/* comet-admin-lang/
              - cd comet-admin-lang
              - git config user.email "vivid-planet-bot@vivid-planet.com"
              - git add .
              - if [[ `git status --porcelain` ]]; then git commit -m "add translatable strings for $TRAVIS_COMMIT" && git remote rm origin && git remote add origin https://vivid-planet-bot:${GH_TOKEN}@github.com/vivid-planet/comet-admin-lang.git && git push --set-upstream origin master; fi

addons:
    apt:
        update: true
