language: node_js
node_js:
    - "8"
cache: yarn
before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
    - yarn
    - yarn build
script:
    - git reset --soft origin/${TRAVIS_BRANCH}
    - yarn lint-staged
