name: CI

on:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - closed
        branches:
            - main
            - next

jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ github.actor }}"

            - uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GH_TOKEN }}

            - run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com

            - name: Use Node.js 14.x
              uses: actions/setup-node@v3
              with:
                  node-version: 14
                  registry-url: "https://registry.npmjs.org"
                  cache: "yarn" # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies

            - run: yarn install

            - name: Copy schema files
              run: |
                  cp packages/api/api-cms/block-meta.json packages/admin/admin-blocks/block-meta.json
                  cp packages/api/api-cms/schema.gql packages/admin/admin-cms/schema.gql
                  cp packages/api/api-cms/block-meta.json packages/admin/admin-cms/block-meta.json
                  cp packages/api/api-cms/block-meta.json packages/site/site-cms/block-meta.json

            - name: Build
              run: yarn build

            - name: Lint
              run: |
                  yarn exec prettier -c .
                  yarn lint

            - name: Test
              run: yarn test

            - name: Test Report
              uses: dorny/test-reporter@v1
              if: success() || failure()
              with:
                  name: Tests
                  path: packages/**/junit.xml
                  reporter: jest-junit

            - name: Extract i18n strings
              if: ${{ github.ref_name == 'main' }}
              run: |
                  yarn intl:extract
                  git clone https://github.com/vivid-planet/comet-admin-lang.git
                  cp -r lang/* comet-admin-lang/
                  cd comet-admin-lang
                  git add .
                  if [[ `git status --porcelain` ]]; then git commit -m "add translatable strings for ${{ github.sha }}" && git remote rm origin && git remote add origin https://vivid-planet-bot:${{ secrets.GH_TOKEN }}@github.com/vivid-planet/comet-admin-lang.git && git push --set-upstream origin master; fi

            - name: Publish premajor canary release
              if: |
                  github.event.label.name != 'skip-release' &&
                  github.base_ref == 'next' &&
                  github.event.pull_request.merged == true
              run: yarn publish:release premajor --no-push --no-git-tag-version --canary --preid=canary.${{ github.run_number }} --dist-tag=canary --yes
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish stable minor release
              if: |
                  github.event.label.name != 'skip-release' &&
                  github.base_ref == 'main' &&
                  github.event.pull_request.merged == true
              run: yarn publish:release minor --yes
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
