name: Release Canary

on:
  push:
    branches:
      - main
      - next

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release-canary:
    name: Release Canary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm" # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Publish Canary release
        run: |
        run: |
          echo --- > .changeset/canary.md
          echo '"@comet/cli": patch' >> .changeset/canary.md
          echo --- >> .changeset/canary.md
          echo >> .changeset/canary.md
          echo fake change to always get a canary release >> .changeset/canary.md
          pnpm exec changeset version --snapshot canary
          pnpm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
