name: Release Canary

on:
  push:
    branches:
      - main
      - next

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release-canary:
    name: Release Canary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm" # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Publish Canary release
        run: |
          pnpm exec changeset version --snapshot canary
          pnpm run build:lib
          pnpm publish --recursive  --filter '@comet/*'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
