name: "Test Report"
on:
    workflow_run:
        workflows: ["Lint"]
        types:
            - completed
jobs:
    report:
        runs-on: ubuntu-latest
        steps:
            - uses: dorny/test-reporter@v1
              with:
                  artifact: test-results
                  name: Tests
                  path: packages/**/junit.xml
                  reporter: jest-junit
